[package]
name = "simalloc"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.3.2"
rand = "0.9.0"
rand_distr = "0.5.0"
rustix = { version = "0.38.44", features = ["mm"] }

[profile.release]
lto = "fat"
